Repository hassio-addons/addon-node-red, pull requests merged in 2021-11, with the labels that each got.

#1162 ⬆️ Upgrades nodejs to 14.18.1-r0
  node-red/Dockerfile
Labels: dependencies

#1163 Switch to centralized GitHub Action Workflows
  .github/labels.yml
  .github/release-drafter.yml
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
  .github/workflows/labels.yaml
  .github/workflows/lock.yaml
  .github/workflows/pr-labels.yaml
  .github/workflows/release-drafter.yaml
  .github/workflows/stale.yaml
Labels: ci

#1164 Migrate JSON config to YAML
  node-red/build.json
  node-red/build.yaml
  node-red/config.json
  node-red/config.yaml
Labels: refactor

#1166 ⬆️ Upgrades add-on base image to 10.2.0
  node-red/Dockerfile
  node-red/build.yaml
Labels: dependencies

#1155 Add links to nodered.org in the documentation
  README.md
  node-red/DOCS.md
Labels: documentation

#1171 ⬆️ Upgrades add-on base image to 10.2.2
  node-red/Dockerfile
  node-red/build.yaml
Labels: dependencies

#1176 Set minimum node version to 12
  node-red/package.json
Labels: maintenance

#1184 ⬆️ Upgrades nginx to 1.20.2-r0
  node-red/Dockerfile
  node-red/build.yaml
Labels: dependencies

#1193 ⬆️ Upgrades add-on base image to 11.0.0
  node-red/Dockerfile
  node-red/build.yaml
Labels: dependencies, minor

#1194 Add Internationalization Support
  node-red/Dockerfile
  node-red/package.json
Labels: enhancement
