Repository hassio-addons/addon-node-red, pull requests merged in 2021-04, with the labels that each got.

#965 ⬆️ Upgrades nodejs to 14.16.1-r0
  node-red/Dockerfile
Labels: dependencies

#966 ⬆️ Upgrades add-on base image to v9.1.7
  node-red/Dockerfile
  node-red/build.json
Labels: dependencies

#974 Remove note about secrets, generic feature now
  node-red/DOCS.md
Labels: documentation

#975 ⬆️ Upgrades nodejs to 14.16.1-r1
  node-red/Dockerfile
Labels: dependencies

#984 📚 Update screenshot link
  node-red/.README.j2
Labels: documentation

#986 Upgrades add-on base image to v9.2.0
  node-red/Dockerfile
  node-red/build.json
Labels: dependencies

#987 Apply updated repository structure & CI workflow
  .editorconfig
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/SECURITY.md
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
  .github/workflows/pr-labels.yaml
Labels: ci

#970 Add support for the theme collection
  node-red/DOCS.md
  node-red/config.json
  node-red/package.json
  node-red/rootfs/etc/cont-init.d/node-red.sh
  node-red/rootfs/etc/node-red/config.js
Labels: new-feature

#989 ⬆️ Upgrades Node-RED to v1.3.3
  node-red/package.json
Labels: dependencies

#990 Fix node-red deployment slug
  .github/workflows/deploy.yaml
Labels: bugfix

#991 Bump @node-red-contrib-themes/theme-collection from 1.0.0 to 1.0.1
  node-red/package.json
Labels: dependencies

#993 Fix theme option overriding user settings
  node-red/rootfs/etc/node-red/config.js
Labels: bugfix
