Repository hassio-addons/addon-node-red, pull requests merged in 2021-12, with the labels that each got.

#1197 ⬆️ Upgrades nodejs to 16.13.1-r0
  node-red/Dockerfile
Labels: dependencies

#1196 ⬆️ Upgrades Node-RED to v2.1.4
  node-red/package.json
Labels: dependencies

#1217 :rocket: Update CI to latest version
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
  .github/workflows/labels.yaml
  .github/workflows/lock.yaml
  .github/workflows/pr-labels.yaml
  .github/workflows/release-drafter.yaml
  .github/workflows/stale.yaml
Labels: ci

#1226 🔨 Add safe mode startup option
  node-red/DOCS.md
  node-red/config.yaml
  node-red/rootfs/etc/services.d/nodered/run
Labels: enhancement
