Repository hassio-addons/addon-node-red, pull requests merged in 2022-06, with the labels that each got.

#1356 ⬆️ Upgrades add-on base image to 12.0.0
  node-red/Dockerfile
  node-red/build.yaml
  node-red/package.json
  node-red/rootfs/etc/cont-init.d/customizations.sh
  node-red/rootfs/etc/cont-init.d/nginx.sh
  node-red/rootfs/etc/cont-init.d/node-red.sh
  node-red/rootfs/etc/services.d/nginx/finish
  node-red/rootfs/etc/services.d/nginx/run
  node-red/rootfs/etc/services.d/nodered/finish
  node-red/rootfs/etc/services.d/nodered/run
Labels: dependencies, minor

#1358 :books: Use new My Home Assistant link format
  node-red/DOCS.md
Labels: documentation

#1357 :ambulance: Fix serial port binding issue
  node-red/Dockerfile
Labels: bugfix

#1360 :fire: Remove GPIO support
  node-red/Dockerfile
  node-red/config.yaml
  node-red/requirements.txt
Labels: breaking-change, maintenance

#1361 :broom: Clean up another 5Mb of cache files
  node-red/Dockerfile
Labels: maintenance

#1362 Clean up gpio node
  node-red/package.json
Labels: maintenance
