Repository hassio-addons/addon-node-red, pull requests merged in 2022-02, with the labels that each got.

#1259 🔨 Reorganize palette categories order
  node-red/rootfs/etc/node-red/settings.js
Labels: enhancement

#1260 🔨 Remove node-red-contrib-actionflows
  node-red/package.json
Labels: breaking-change, bugfix

#1274 ⬆️ Upgrades nodejs to 16.14.0-r0
  node-red/Dockerfile
Labels: dependencies

#1275 :sparkles: Add support for setting max_old_space_size
  node-red/DOCS.md
  node-red/config.yaml
  node-red/rootfs/etc/services.d/nodered/run
Labels: new-feature

#1281 Change minimum Home Assistant version to 2021.3.0
  node-red/config.yaml
Labels: bugfix

#1290 :ambulance: Add workaround for modbus node
  node-red/package.json
Labels: bugfix
