Repository hassio-addons/addon-node-red, pull requests merged in 2023-03, with the labels that each got.

#1566 ⬆️ Upgrades add-on base image to 13.1.3
  node-red/Dockerfile
  node-red/build.yaml
Labels: dependencies

#1574 Add Renovate for dependency management
  .github/dependabot.yaml
  .github/renovate.json
  node-red/Dockerfile
Labels: maintenance

#1579 Apply Node-RED dashboard patch at build time
  node-red/Dockerfile
  node-red/node-red-dashboard-show-dashboard.patch
  node-red/rootfs/etc/s6-overlay/s6-rc.d/init-nodered/run
Labels: enhancement

#1580 Fix broken URL
  node-red/DOCS.md
Labels: documentation
